export const COLUMN_TYPES = [
  'BIGINT', 'INT', 'SMALLINT', 'TINYINT', 'DECIMAL', 'FLOAT', 'DOUBLE',
  'CHAR', 'VARCHAR', 'TEXT', 'MEDIUMTEXT', 'LONGTEXT',
  'DATE', 'DATETIME', 'TIMESTAMP', 'JSON',
];

export const LENGTH_TYPES = ['CHAR', 'VARCHAR', 'DECIMAL'];
